### PR TITLE
Feat/various exchange fixes

### LINKED ISSUE #2186: UI Usability Suggestion
Allow user to start typing their country name to select from drop-down list.

### LINKED ISSUE #2224: small typo (english ui)
change:

Thanks for registering a user on the marketplace

to:

Thanks for registering as a user on the marketplace

### LINKED ISSUE #2226: UI not localizing org users table
Most of the UI is using string lookups to localize output, but in the OrganizationUsersTable.tsx there are some hard-code strings for the table headers:

    const columns = [
        { id: 'firstName', label: 'First name' },
        { id: 'lastName', label: 'Last name' },
        { id: 'email', label: 'Email' },
        { id: 'role', label: 'Role' }
    ];

### LINKED ISSUE #2228: Approve on already approved Orgs
I'm getting an approve action popup on orgs which have already been approved:

Screen Shot 2021-03-23 at 10 42 26 AM

### PR DESCRIPTION
**Pull request by marcin-l-tsh**
* removed Facility Name filter from Bids table
* fixed remaining last item in bid/demand table after removal
* fixed price bug in exchange inbox when entering float value
* changed modal information after registering IRec organisation
* fixed few translations
* fixed display of 'approve' button for already approved organisations
* replaced country select inputs with autocompleting selects 

Fixes #2224
Fixes #2226
Fixes #2228
Fixes #2186

### CODE REVIEW

File: packages/ui/origin-ui-core/src/components/Modal/IRecAccountRegisteredModal.tsx [hunk 1]
```diff
@@ -1,45 +1,29 @@
...
-import { showNotification, NotificationType } from '../../utils/notifications';
-import { useLinks } from '../../utils/routing';
+import { showNotification, NotificationType } from '../../utils';
 import iconAdded from '../../../assets/icon-org-added.svg';
 
 interface IProps {
     showModal: boolean;
     setShowModal: (showModal: boolean) => void;
-    setShowBlockchainModal?: (showModal: boolean) => void;
+    onClose?: (showModal: boolean) => void;
```
Comment (alexworker23) [inline packages/ui/origin-ui-core/src/components/Modal/IRecAccountRegisteredModal.tsx]: This naming is misleading, because now it looks like event handler, but actually it is a setState function passed as prop.

File: packages/ui/origin-ui-core/src/components/certificates/ExchangeInboxPage.tsx [hunk 2]
```diff
@@ -128,16 +128,19 @@ export function ExchangeInboxPage(): JSX.Element {
                                     type="number"
                                     value={price}
                                     onChange={(ev) => {
-                                        const newValue = parseFloat(ev.target.value);
-                                        if (!isNaN(newValue)) setPrice(newValue);
+                                        const newValue = parseFloat(
+                                            ev.target.value.replace(',', '.')
+                                        );
+                                        if (!isNaN(newValue))
+                                            setPrice(Math.floor(newValue * 100) / 100);
```
Comment (alexworker23) [inline packages/ui/origin-ui-core/src/components/certificates/ExchangeInboxPage.tsx]: Currently I am unable to write a number with dot, only numbers with comma could be typed into this input. 
Please, check.

**Review by alexworker23 — COMMENTED** [review]
Another bugs to be worked on: 
1. In Exchange inbox:
- select certificate
- type a long price number
- page crushes and console errors 
2. Removing last item from Table is not fixed in: 
- Open Asks inside My Orders
- Bundles tables
3. Bids filters for Start and End date should be in one line. Device type filter could be moved down.

**Review by alexworker23 — APPROVED** [review]
